// This file is auto-generated by @hey-api/openapi-ts

export { claimSeat, type Options, readRoom } from './sdk.gen';
export type { ClaimSeatData, ClaimSeatError, ClaimSeatErrors, ClaimSeatResponse, ClaimSeatResponses, ClientOptions, Game, HttpValidationError, Identity, ReadRoomData, ReadRoomResponse, ReadRoomResponses, Room, Seat, ValidationError } from './types.gen';
