// This file is auto-generated by @hey-api/openapi-ts

export { type Options, readMe, readRoom, renameMe } from './sdk.gen';
export type { ClientOptions, Game, HttpValidationError, Identity, Me, Person, ReadMeData, ReadMeResponse, ReadMeResponses, ReadRoomData, ReadRoomResponse, ReadRoomResponses, RenameMeData, RenameMeError, RenameMeErrors, RenameMeResponse, RenameMeResponses, Room, Seat, ValidationError } from './types.gen';
