// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ClaimSeatData, ClaimSeatErrors, ClaimSeatResponses, ReadMeData, ReadMeResponses, ReadRoomData, ReadRoomResponses, RenameMeData, RenameMeErrors, RenameMeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Read Me
 *
 * L'identité que le proxy garantit, et le pseudo qui va avec.
 *
 * Rend `login: null` quand aucun proxy n'est devant, ce qui est le cas en
 * développement. Ce n'est pas une erreur: la page retombe alors sur un prénom
 * gardé dans le navigateur, comme avant.
 */
export const readMe = <ThrowOnError extends boolean = false>(options?: Options<ReadMeData, ThrowOnError>): RequestResult<ReadMeResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadMeResponses, unknown, ThrowOnError>({ url: '/api/me', ...options });

/**
 * Rename Me
 *
 * Change son propre pseudo, et rien d'autre.
 *
 * Le pseudo est écrit sous l'adresse que le PROXY donne, jamais sous une
 * adresse envoyée par le client: c'est la différence entre choisir son nom et
 * choisir celui de quelqu'un d'autre.
 */
export const renameMe = <ThrowOnError extends boolean = false>(options: Options<RenameMeData, ThrowOnError>): RequestResult<RenameMeResponses, RenameMeErrors, ThrowOnError> => (options.client ?? client).put<RenameMeResponses, RenameMeErrors, ThrowOnError>({
    url: '/api/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Room
 *
 * What is loaded, what else could be, who claims which pad, and who is here.
 */
export const readRoom = <ThrowOnError extends boolean = false>(options?: Options<ReadRoomData, ThrowOnError>): RequestResult<ReadRoomResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadRoomResponses, unknown, ThrowOnError>({ url: '/api/room', ...options });

/**
 * Claim Seat
 *
 * Records that a player claims a pad.
 *
 * The worker decides who really holds it; this is the name to show beside it.
 *
 * The name travels in the BODY, not in a query string. It is not a secret, but
 * a URL is written to every log between a browser and here, and a name is still
 * a person. The lobby socket already passes it that way, and an endpoint that
 * disagreed with the socket beside it would be a rule nobody could state.
 */
export const claimSeat = <ThrowOnError extends boolean = false>(options: Options<ClaimSeatData, ThrowOnError>): RequestResult<ClaimSeatResponses, ClaimSeatErrors, ThrowOnError> => (options.client ?? client).post<ClaimSeatResponses, ClaimSeatErrors, ThrowOnError>({
    url: '/api/room/seats/{port}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
