// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Bindings
 *
 * Ce que quelqu'un a réglé sur ses manettes et son clavier.
 *
 * Le contenu est OPAQUE au service, et c'est délibéré. La forme d'un profil
 * appartient à la page: elle sait ce qu'un axe, un repos et un signe veulent
 * dire, et elle est la seule à s'en servir. La décrire ici en donnerait une
 * deuxième version à tenir d'accord avec la première, et il faudrait publier le
 * service pour ajouter un champ à une manette.
 *
 * Ce qui est vérifié est ce qui protège le disque: un objet, sous un plafond
 * (voir `BindingsController.CEILING`).
 */
export type Bindings = {
    /**
     * Pads
     *
     * Un profil par manette, indexé par l'identifiant que le navigateur donne.
     */
    pads?: {
        [key: string]: unknown;
    };
    /**
     * Keys
     *
     * Ce que chaque touche du clavier fait, indexé par sa POSITION physique.
     */
    keys?: {
        [key: string]: unknown;
    };
};

/**
 * Game
 *
 * One game the room can run.
 */
export type Game = {
    /**
     * Index
     *
     * Its position in the worker's library, which is how it is asked for.
     */
    index: number;
    /**
     * Name
     *
     * What to call it on screen.
     */
    name: string;
    /**
     * Maker
     *
     * Qui l'a fait, tel que le disque le dit lui-même. Nul quand le disque n'a pas donné sa jaquette.
     */
    maker?: string | null;
    /**
     * About
     *
     * La phrase que l'éditeur a écrite sur le disque. Peut contenir un retour à la ligne: ces textes ont été mis en page sur deux lignes.
     */
    about?: string | null;
    /**
     * Console
     *
     * Quelle console ce disque demande, lue sur le disque: « gc », « wii », ou « ? » quand le disque n'a pas répondu. La page s'en sert pour ne pas proposer un choix qui ne déciderait rien: un jeu Wii n'a pas de carte mémoire, donc pas deux emplacements de sauvegarde. « ? » n'est pas « gc »: proposer un choix qui ne fait rien est pire que ne pas le proposer.
     */
    console?: string;
    /**
     * Art
     *
     * Vrai quand le worker sert une image pour ce jeu, à /art/{index}.png. Un booléen plutôt qu'une adresse: le chemin appartient au worker, et le recopier ici en ferait une deuxième vérité à tenir à jour.
     */
    art?: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Identity
 *
 * A person, as this service knows them.
 *
 * There is no account and no password: rooms are private and shared with people
 * already on the network. The name exists so a seat can say "Souhib" rather than
 * "player 2" (ADR D12).
 */
export type Identity = {
    /**
     * Name
     */
    name: string;
};

/**
 * Me
 *
 * Qui le service croit avoir en face.
 *
 * `login` vient du proxy et n'est pas modifiable; `name` est choisi et l'est.
 * Un `login` nul veut dire « aucun proxy devant », donc aucune identité: la
 * page retombe alors sur un prénom gardé dans le navigateur.
 */
export type Me = {
    /**
     * Login
     *
     * L'adresse que Tailscale garantit, ou rien.
     */
    login?: string | null;
    /**
     * Name
     *
     * Le pseudo, choisi et modifiable.
     */
    name: string;
    /**
     * Display
     *
     * Le nom que le fournisseur d'identité affiche, pour information.
     */
    display?: string;
    /**
     * Publishes
     *
     * Cette personne peut-elle publier la configuration de référence de la salle ? Un booléen et non l'adresse de qui le peut: la page a besoin de savoir ce qu'ELLE peut faire, pas de connaître l'adresse de quelqu'un d'autre.
     */
    publishes?: boolean;
};

/**
 * Person
 *
 * Quelqu'un dans la salle, qu'il tienne une manette ou non.
 */
export type Person = {
    /**
     * Name
     */
    name: string;
    /**
     * Login
     */
    login?: string | null;
    /**
     * Seat
     *
     * La manette qu'il tient, s'il en tient une.
     */
    seat?: number | null;
};

/**
 * Room
 *
 * The room, as a page needs to render it.
 */
export type Room = {
    /**
     * Name
     */
    name: string;
    /**
     * What is loaded right now.
     */
    game?: Game | null;
    /**
     * Library
     */
    library: Array<Game>;
    /**
     * Seats
     */
    seats: Array<Seat>;
    /**
     * Qui décide du jeu: le premier arrivé encore présent. Nul quand personne n'a d'identité, et la salle retombe alors sur sa règle d'avant, où tenir une manette suffit.
     */
    owner?: Person | null;
    /**
     * People
     *
     * Tout le monde dans la salle, spectateurs compris. Les places ne disent que ceux qui jouent, et une salle où quelqu'un regarde sans manette avait l'air vide.
     */
    people?: Array<Person>;
    /**
     * Ask Lasts
     *
     * Combien de secondes une demande de manette attend une réponse. Publié pour que le compte à rebours de la page soit le vrai, et non un nombre recopié qui finirait par ne plus correspondre.
     */
    ask_lasts?: number;
    /**
     * Media Url
     *
     * Where the browser opens its own video, sound and pad sockets. Empty means the page's own origin.
     */
    media_url: string;
};

/**
 * Seat
 *
 * One of the room's pads, and who claims it.
 */
export type Seat = {
    /**
     * Port
     */
    port: number;
    /**
     * Player
     *
     * The name of whoever claims it, if anybody.
     */
    player?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type ReadMeResponses = {
    /**
     * Successful Response
     */
    200: Me;
};

export type ReadMeResponse = ReadMeResponses[keyof ReadMeResponses];

export type RenameMeData = {
    body: Identity;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type RenameMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RenameMeError = RenameMeErrors[keyof RenameMeErrors];

export type RenameMeResponses = {
    /**
     * Successful Response
     */
    200: Me;
};

export type RenameMeResponse = RenameMeResponses[keyof RenameMeResponses];

export type ReadBindingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me/bindings';
};

export type ReadBindingsResponses = {
    /**
     * Successful Response
     */
    200: Bindings;
};

export type ReadBindingsResponse = ReadBindingsResponses[keyof ReadBindingsResponses];

export type KeepBindingsData = {
    body: Bindings;
    path?: never;
    query?: never;
    url: '/api/me/bindings';
};

export type KeepBindingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KeepBindingsError = KeepBindingsErrors[keyof KeepBindingsErrors];

export type KeepBindingsResponses = {
    /**
     * Successful Response
     */
    200: Bindings;
};

export type KeepBindingsResponse = KeepBindingsResponses[keyof KeepBindingsResponses];

export type ReadRoomData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/room';
};

export type ReadRoomResponses = {
    /**
     * Successful Response
     */
    200: Room;
};

export type ReadRoomResponse = ReadRoomResponses[keyof ReadRoomResponses];

export type ReadRoomBindingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/room/bindings';
};

export type ReadRoomBindingsResponses = {
    /**
     * Successful Response
     */
    200: Bindings;
};

export type ReadRoomBindingsResponse = ReadRoomBindingsResponses[keyof ReadRoomBindingsResponses];

export type PublishRoomBindingsData = {
    body: Bindings;
    path?: never;
    query?: never;
    url: '/api/room/bindings';
};

export type PublishRoomBindingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PublishRoomBindingsError = PublishRoomBindingsErrors[keyof PublishRoomBindingsErrors];

export type PublishRoomBindingsResponses = {
    /**
     * Successful Response
     */
    200: Bindings;
};

export type PublishRoomBindingsResponse = PublishRoomBindingsResponses[keyof PublishRoomBindingsResponses];
