// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Game
 *
 * One game the room can run.
 */
export type Game = {
    /**
     * Index
     *
     * Its position in the worker's library, which is how it is asked for.
     */
    index: number;
    /**
     * Name
     *
     * What to call it on screen.
     */
    name: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Identity
 *
 * A person, as this service knows them.
 *
 * There is no account and no password: rooms are private and shared with people
 * already on the network. The name exists so a seat can say "Souhib" rather than
 * "player 2" (ADR D12).
 */
export type Identity = {
    /**
     * Name
     */
    name: string;
};

/**
 * Room
 *
 * The room, as a page needs to render it.
 */
export type Room = {
    /**
     * Name
     */
    name: string;
    /**
     * What is loaded right now.
     */
    game?: Game | null;
    /**
     * Library
     */
    library: Array<Game>;
    /**
     * Seats
     */
    seats: Array<Seat>;
    /**
     * Media Url
     *
     * Where the browser opens its own video, sound and pad sockets. Empty means the page's own origin.
     */
    media_url: string;
};

/**
 * Seat
 *
 * One of the room's pads, and who claims it.
 */
export type Seat = {
    /**
     * Port
     */
    port: number;
    /**
     * Player
     *
     * The name of whoever claims it, if anybody.
     */
    player?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadRoomData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/room';
};

export type ReadRoomResponses = {
    /**
     * Successful Response
     */
    200: Room;
};

export type ReadRoomResponse = ReadRoomResponses[keyof ReadRoomResponses];

export type ClaimSeatData = {
    body: Identity;
    path: {
        /**
         * Port
         */
        port: number;
    };
    query?: never;
    url: '/api/room/seats/{port}';
};

export type ClaimSeatErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ClaimSeatError = ClaimSeatErrors[keyof ClaimSeatErrors];

export type ClaimSeatResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ClaimSeatResponse = ClaimSeatResponses[keyof ClaimSeatResponses];
