import puppeteer from "puppeteer";
const browser = await puppeteer.launch({ headless: true, args: ["--no-sandbox"] });
const page = await browser.newPage();
page.on("console", (m) => console.log("CONSOLE:", m.type(), m.text()));
page.on("pageerror", (e) => console.log("PAGEERROR:", e.message));
await page.goto("http://localhost:5199/padmap-preview.html", { waitUntil: "networkidle0" });
await new Promise((r) => setTimeout(r, 1500));
const n = await page.evaluate(() => document.querySelectorAll("[data-padmap]").length);
console.log("nb svg:", n);
console.log((await page.evaluate(() => document.body.innerText.slice(0, 200))));
await browser.close();
